medikago/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import home
from authentication.views import profile

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('auth/', include('authentication.urls'), name='authentication'),
    path('profil', profile, name="profile"),
    path('transaksi/', include('transaksi.urls'), name='transaksi'),
    path('rscabang/', include('rscabang.urls'), name='rscabang'),
    path('sesikonsultasi/', include('sesikonsultasi.urls'), name='sesikonsultasi'),
    path('poliklinik/', include('poliklinik.urls'), name='poliklinik'),
    path('resep-obat/', include('resepdanobat.urls'), name='resepdanobat')
]

rscabang/urls.py
from django.urls import path
from . import views

app_name='rscabang'
urlpatterns = [
    path('buat-rscabang/', views.buat_rscabang, name='buat_rscabang'),  #untuk menu Buat RS Cabang
    path('daftar-rscabang/', views.daftar_rscabang, name='daftar_rscabang'),    #untuk menu Daftar RS Cabang
    path('daftar-rscabang/<int:koders>', views.update_rscabang, name='update_rscabang'), #untuk action update Daftar RS Cabang
    path('daftar-rscabang/delete/<int:koders>', views.delete_rscabang, name='delete_rscabang'),
    path('add_dokter/', views.add_dokter, name='add_dokter'),    #untuk  Daftarkan Dokter
    path('list_dokter/', views.list_dokter, name='list_dokter'),    #untuk menu Daftar Dokter-RS Cabang
    path('list_dokter/<slug:kode_rs>/<slug:id_dokter>', views.update_dokter, name='update_dokter'), #menu untuk action update di tabel daftar dokter
    path('list_dokter/delete/<slug:kode_rs>/<slug:id_dokter>', views.delete_pair, name='delete_pair'),  #menu untuk delete pair RS Cabang-Dokter RS Cabang
    path('daftarkan-administrator/', views.daftarkan_administrator, name='daftarkan_administrator'),    #untuk menu Daftarkan Administrator
]

rscabang/models.py
from django.db import models

# Create your models here.

rscabang/views.py
from django.shortcuts import render, redirect
from .db import RSCabang, Admin
from authentication.auth import login_required, admin_permission

'''View for Buat RS Cabang menu'''
@login_required
@admin_permission
def buat_rscabang(request):
    error = False
    if request.method == 'POST':
        kode = request.POST['kode']
        nama = request.POST['nama']
        tanggal = request.POST['tanggal']
        jalan = request.POST['jalan']
        nomor = request.POST['nomor']
        kota = request.POST['kota']
        try: 
            RSCabang().create_rs_cabang(kode, nama, tanggal, jalan, nomor, kota)
            return redirect("rscabang:daftar_rscabang")
        except:
            error = True
    kode_terakhir = RSCabang().get_last_koder()
    kode = kode_terakhir[0]['max'] +1
    return render(request, 'buat-rscabang.html', {'kode':kode, 'error': error})

'''View for Daftar RS Cabang menu'''
@login_required
def daftar_rscabang(request):
    list_rs_cabang = RSCabang().get_list_daftar_cabang()
    return render(request, 'daftar-rscabang.html', {'list_rscabang':list_rs_cabang})

'''View for updating data RS Cabang'''
@login_required
@admin_permission
def update_rscabang(request, koders):
    error = False
    rs = RSCabang().get_detailed_rs(koders)
    tanggal = str(rs[0]['tanggal_pendirian'])
    if request.method == 'POST':
        kode = koders
        nama = request.POST['nama']
        tanggal = request.POST['tanggal']
        jalan = request.POST['jalan']
        nomor = request.POST['nomor']
        kota = request.POST['kota']
        try:
            RSCabang().update_detailed_rs(kode, nama, tanggal, jalan, nomor, kota)
            return redirect("rscabang:daftar_rscabang")
        except:
            error = True
            pass
    return render(request, 'update_rscabang.html', {'rs':rs[0], 'tanggal':tanggal, "error":error})

@login_required
@admin_permission
def delete_rscabang(request, koders):
    if request.method == 'POST':
        RSCabang().delete(koders)
    return redirect("rscabang:daftar_rscabang")

'''Views for Daftarkan Dokter'''
@login_required
@admin_permission
def add_dokter(request):
    error=False
    if request.method == 'POST':
        id_dokter = request.POST['id_dokter']
        kode_rs = request.POST['kode_rs']
        try:
            RSCabang().add_dokter_rs_cabang(id_dokter, kode_rs)
            return redirect("rscabang:list_dokter")
        except:
            error=True
            pass
    list_id_dokter= RSCabang().get_all_id_dokter()
    list_kode_rs = RSCabang().get_all_kode_rs()
    return render(request, 'add_dokter.html', {"error":error,"list_id_dokter":list_id_dokter, "list_kode_rs":list_kode_rs})

'''Views for outputing all dokter-RS Cabang'''
@login_required
def list_dokter(request):
    list_pair_items = RSCabang().get_all_pair_kodeRS_idDokter()
    list_kodeRS = RSCabang().get_all_kodeRS_from_pair()
    return render(request, 'list_dokter.html', {"list_pair_items":list_pair_items, "list_kodeRS":list_kodeRS})

'''View for Updating data dokter-RS Cabang'''
@login_required
@admin_permission
def update_dokter(request, kode_rs, id_dokter):
    error = False
    old_kode_rs = kode_rs
    old_id_dokter = id_dokter
    detail_old_dokter = RSCabang().get_detail_dokter_by_id(id_dokter)
    detail_old_rs = RSCabang().get_detail_rs_by_id(kode_rs)
    list_kodeRS = RSCabang().get_all_kode_rs()
    list_idDokter = RSCabang().get_all_id_dokter()
    if request.method=="POST":
        new_kode_rs = request.POST['kode_rs']
        new_id_dokter = request.POST['id_dokter']
        try:
            RSCabang().update_pair(old_kode_rs, old_id_dokter, new_kode_rs, new_id_dokter)
            return redirect("rscabang:list_dokter")
        except:
            error = True
            pass 
    return render(
        request, 'update-dokter.html',
        {"old_kode_rs":old_kode_rs, "old_id_dokter":old_id_dokter, "list_kodeRS":list_kodeRS, "list_idDokter":list_idDokter, "detail_old_dokter":detail_old_dokter,
        "detail_old_rs":detail_old_rs, "error":error}
    )

'''View for Deleting pair Dokter-RS Cabang'''
@login_required
@admin_permission
def delete_pair(request, kode_rs, id_dokter):
    if request.method == "POST":
        RSCabang().delete_pair(kode_rs, id_dokter)
    return redirect('rscabang:list_dokter')

'''View for Daftarkan Administrator menu'''
@login_required
@admin_permission
def daftarkan_administrator(request):
    error = False
    if request.method == "POST":
        no_pegawai = request.POST['nomor_pegawai']
        kode_rs = request.POST['kode_rs']
        try:
            Admin().assign_new_rs(no_pegawai, kode_rs)
            return redirect('rscabang:daftar_rscabang')
        except:
            error = True
    list_rs_cabang = RSCabang().get_list_daftar_cabang()
    list_admin = Admin().get_all_nomor_pegawai()
    response = {
        'list_rs_cabang' : list_rs_cabang,
        'list_admin' : list_admin,
        'error' : error
    }
    return render(request, 'daftarkan-administrator.html', response)

rscabang/templates/add_dokter.html
{% extends 'base.html' %}

{% block content %}
<div class="d-flex flex-column align-items-center">
    <h2>FORM PENDAFTARAN DOKTER RS CABANG</h2>
    <div class=" mt-4 w-25">
        {% if error %}
            <h3 class="text-warning">Integrity Error, please change your input!</h3>
        {% endif %}
        <form action="{% url 'rscabang:add_dokter' %}" method="POST" class="align-items-center" >
            {% csrf_token %}
            <div class="d-flex flex-row form-group-row my-2">
                <p class="w-25">ID Dokter</p>
                <select name="id_dokter" id="" class="custom-select w-75">
                    {% for item in list_id_dokter %}
                        <option value="{{ item.id_dokter }}">{{ item.id_dokter }} - {{ item.username }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="d-flex flex-row form-group-row my-2">
                <p class="w-25">Kode RS</p>
                <select name="kode_rs" id="" class="custom-select w-75">
                    {% for item in list_kode_rs %}
                        <option value="{{ item.kode_rs }}">{{ item.kode_rs }} - {{ item.nama }}</option>
                    {% endfor %}
                </select>
            </div>
            <input type="submit" value="Submit" class="btn btn-outline-info float-right mt-2">
        </form>
    </div>
</div>

{% endblock %}

rscabang/templates/buat-rscabang.html
{% extends 'base.html' %}

{% block content %}
<div class="d-flex flex-column align-items-center">
    <h2>FORM FORM PEMBUATAN RS CABANG</h2>
    <div class=" mt-4 w-50">
        <form action="{% url 'rscabang:buat_rscabang' %}" method="POST" class="align-items-center" onclick="ilanginError()">
            {% csrf_token %}
            <p class="text-danger" id="error-message">
                {% if error %}
                    kode RS cabang tersebut sudah ada atau beberapa input tidak sesuai, silakan coba lagi
                {% endif %}
            </p>
            <div class="d-flex flex-row form-group-row my-2">
                <p class="w-25">Kode RS Cabang</p>
                <input type="text" name="kode" class="form-control w-75" value="{{ kode }}" required>
            </div>
            <div class="d-flex flex-row form-group-row my-2">
                <p class="w-25">Nama</p>
                <input type="text" name="nama" class="form-control w-75" required>
            </div>
            <div class="d-flex flex-row form-group-row my-2">
                <p class="w-25">Tanggal Pendirian</p>
                <input type="date" name="tanggal" class="form-control w-75 required">
            </div>
            <div class="d-flex flex-row form-group-row my-2">
                <p class="w-25">Jalan</p>
                <input type="text" name="jalan" class="form-control w-75">
            </div>
            <div class="d-flex flex-row form-group-row my-2">
                <p class="w-25">Nomor</p>
                <input type="text" name="nomor" class="form-control w-75">
            </div>
            <div class="d-flex flex-row form-group-row my-2">
                <p class="w-25">Kota</p>
                <input type="text" name="kota" class="form-control w-75" required>
            </div>
            <input type="submit" value="Submit" class="btn btn-outline-info float-right mt-2">
        </form>
    </div>
</div>

{% endblock %}

{% block script %}
<script>
  function ilanginError(){
    document.getElementById("error-message").innerHTML="";
  }
</script>
{% endblock %}

rscabang/templates/daftar-rscabang.html
{% extends 'base.html' %}

{% block content %}
<h2 class="mt-4 mb-3 ml-3">Daftar RS Cabang</h1>
  <table class="table table-hover">
    <thead>
      <tr>
        <th scope="col">Kode RS</th>
        <th scope="col">Nama</th>
        <th scope="col">Tanggal Pendirian</th>
        <th scope="col">Jalan</th>
        <th scope="col">Kota</th>
        <th scope="col">Nomor</th>
        {% if request.session.role == 'admin' %}
        <th scope="col">Action</th>
        {% endif %}
      </tr>
    </thead>
    <tbody>
      {% for rs in list_rscabang %}
      <tr>
        <td>{{ rs.kode_rs }}</td>
        <td>{{ rs.nama }}</td>
        <td>{{ rs.tanggal_pendirian }}</td>
        <td>{{ rs.jalan }}</td>
        <td>{{ rs.kota }}</td>
        <td>{{ rs.nomor }}</td>
        {% if request.session.role == 'admin' %}
        <td>
          <div class="col">
            <button class='btn btn-outline-info btn-sm' onclick="window.location={{ rs.kode_rs }}">Update</button>
            <form method="POST" action="{% url 'rscabang:delete_rscabang' rs.kode_rs %}">
              {% csrf_token %}
              <button class='btn btn-danger' type="submit">Delete</button>
            </form>
          <div>
        </td>
        {% endif %}
      </tr>
      {% endfor %}
    </tbody>
  </table>


  {% endblock %}

rscabang/templates/daftarkan-administrator.html
{% extends 'base.html' %}

{% block content %}
<div class='container'>
    <h1 class='d-flex align-items-center flex-column mt-3 pt-3'>Daftarkan Administrator</h1>

    <form class='d-flex flex-column align-items-center' method="POST" action="{% url 'rscabang:daftarkan_administrator' %}">
    {% csrf_token %}
    {% if error %}
        <p class="text-danger text-center mb-3" id="error-message">
            Terjadi kesalahan
        </p>
    {% endif %}
    <div class='mt-3 d-flex flex-column col-sm-4'>
        <div class="form-group row pl-4">
            <label for="no-pegawai" class="col-sm-5 col-form-label">No. Pegawai</label>
            <div class="col-sm-7">
                <!-- <div class="dropdown">
                    <button class="btn btn-secondary dropdown-toggle" type="button" id="no-pegawai" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        No. Pegawai
                    </button>
                    <div class="dropdown-menu" aria-labelledby="no-pegawai">
                        <button class="dropdown-item" type="button">1</button>
                        <button class="dropdown-item" type="button">2</button>
                        <button class="dropdown-item" type="button">3</button>
                    </div>
                </div> -->
                <select class="custom-select" name="nomor_pegawai" required aria-invalid="false">
                    <option value="" selected disabled>No. Pegawai</option>
                    {% for admin in list_admin %}
                        <option value="{{ admin.nomor_pegawai }}">{{ admin.nomor_pegawai }} - {{ admin.username }}</option>
                    {% endfor %}
                </select>
            </div>
        </div>
        <div class="form-group row pl-4">
            <label for="kode-rs" class="col-sm-5 col-form-label">Kode RS</label>
            <div class="col-sm-7">
                <!-- <div class="dropdown">
                    <button class="btn btn-secondary dropdown-toggle" type="button" id="kode-rs" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Kode RS
                    </button>
                    <div class="dropdown-menu" aria-labelledby="kode-rs">
                        <button class="dropdown-item" type="button">1</button>
                        <button class="dropdown-item" type="button">2</button>
                        <button class="dropdown-item" type="button">3</button>
                    </div>
                </div> -->
                <select class="custom-select" name="kode_rs" required aria-invalid="false">
                    <option value="" selected disabled>Kode RS</option>
                    {% for rs in list_rs_cabang %}
                        <option value="{{ rs.kode_rs }}">{{ rs.kode_rs }} - {{ rs.nama }}</option>
                    {% endfor %}
                </select>
            </div>
        </div>
        <div class='container d-flex align-items-right flex-column'>
            <input type="submit" value="Daftarkan" class="btn btn-danger mt-3">
        </div>
    </div>
    </form>
</div>
{% endblock %}

rscabang/templates/list_dokter.html
{% extends 'base.html' %}

{% block content %}
<h2 class="mt-4 mb-3 ml-3">Daftar Dokter-RS Cabang</h1>
<table class="table table-hover">
    <thead>
      <tr>
        <th scope="col">No.</th>
        <th scope="col">Kode RS Cabang</th>
        <th scope="col">ID Dokter</th>
        {% if request.session.role == "admin" %}
          <th scope="col">Action</th>
        {% endif %} 
      </tr>
    </thead>
    <tbody>
      {% for kodeRS in list_kodeRS %}
        <tr>
          <th scope="row">{{ forloop.counter }}</th>
          <td>{{kodeRS.kode_rs}}</td>
          <td>
            {% for pairs in list_pair_items %}
              {% if pairs.kode_rs == kodeRS.kode_rs %}
                <li class="mb-1">{{ pairs.id_dokter }}</li>
              {% endif %}
            {% endfor %}
          </td>
          {% if request.session.role == "admin" %}
            <td>
              {% for pairs in list_pair_items %}
                {% if pairs.kode_rs == kodeRS.kode_rs %}
                  <li class="mb-1">
                      <button class='btn btn-outline-info btn-sm' onclick="window.location='{{kodeRS.kode_rs}}/{{pairs.id_dokter}}'">Update</button>
                      <form method="POST" action="{% url 'rscabang:delete_pair' kodeRS.kode_rs pairs.id_dokter %}" class='btn btn-sm'>
                        {% csrf_token %}
                        <button class='btn btn-danger btn-sm'>Delete</button>
                      </form>
                  </li>
                {% endif %}
              {% endfor %}
            </td>
          {% endif %}
        </tr>
      {% endfor %}
      <!-- <tr>
        <th scope="row">2</th>
        <td>2</td>
        <td>
            <li class="mb-1">2</li>
            <li class="mb-1">7</li>
        </td>
        <td>
            <li class="mb-1">
                <button class='btn btn-outline-info btn-sm' onclick="window.location='3'">Update</button>
                <button class='btn btn-danger btn-sm'>Delete</button>
            </li>
            <li class="mb-1">
                <button class='btn btn-outline-info btn-sm' onclick="window.location='4'">Update</button>
                <button class='btn btn-danger btn-sm'>Delete</button>
            </li>
        </td>
      </tr> -->
    </tbody>
  </table>


{% endblock %}

rscabang/templates/update-dokter.html
{% extends 'base.html' %}

{% block content %}
<div class="d-flex align-items-center flex-column mt-5 pt-5">
  <h1 class="mb-2">FORM UPDATE DOKTER-RS CABANG</h1>
  <form method="POST" action="{% url 'rscabang:update_dokter' old_kode_rs old_id_dokter %}">
    {% csrf_token %}
    <div class="form-group row">
        <p class="col">ID Dokter</p>
        <select name="id_dokter" id="" class="custom-select">
            <option value="{{ old_id_dokter }}" selected> {{ old_id_dokter }} - {{ detail_old_dokter.username }} </option>
            {% for items in list_idDokter %}
              {% if items.id_dokter != old_id_dokter %}
                <option value="{{ items.id_dokter }}">{{ items.id_dokter }} - {{ items.username }}</option>
              {% endif %}
            {% endfor %}
        </select>
    </div>
    <div class="form-group row">
        <p class="col">Kode RS Cabang</p>
        <select name="kode_rs" id="" class="custom-select">
            <option value="{{ old_kode_rs }}" selected>{{ old_kode_rs }} - {{ detail_old_rs.nama }}</option>
            {% for items in list_kodeRS %}
              {% if items.kode_rs != old_kode_rs %}
                <option value="{{ items.kode_rs }}">{{ items.kode_rs }} - {{ items.nama }}</option>
              {% endif %}
            {% endfor %}
        </select>
    </div>
    <p></p>
    <input type="submit" value="Update" class="btn btn-outline-info float-right">
  </form>
</div>
{% endblock %}

rscabang/templates/update_rscabang.html
{% extends 'base.html' %}

{% block content %}
<div class="d-flex flex-column align-items-center">
    <h2>FORM UPDATE RS Cabang</h2>
    {% if error %}
        <h3 class="text-warning">Error occured, please check your input!</h3>
    {% endif %}
    <div class=" mt-4 w-75">
        <form action="" method="POST" class=" align-items-center">
            {% csrf_token %}
            <div class="d-flex flex-row form-group-row my-2">
                <p class="w-50">Kode RS</p>
                <input type="text" class="form-control" id="disabledTextInput" placeholder="{{ rs.kode_rs }}" disabled>
            </div>
            <div class="d-flex flex-row form-group-row my-2">
                <p class="w-50">Nama</p>
                <input type="text" name="nama" class="form-control" value="{{ rs.nama }}">
            </div>
            <div class="d-flex flex-row form-group-row my-2">
                <p class="w-50">Tanggal Pendirian</p>
                <input type="date" name="tanggal" class="form-control" value="{{ tanggal }}">
            </div>
            <div class="d-flex flex-row form-group-row my-2">
                <p class="w-50">Jalan</p>
                <input type="text" name="jalan" class="form-control" value="{{ rs.jalan }}">
            </div>
            <div class="d-flex flex-row form-group-row my-2">
                <p class="w-50">Kota</p>
                <input type="text" name="kota" class="form-control" value="{{ rs.kota }}">
            </div>
            <div class="d-flex flex-row form-group-row my-2">
                <p class="w-50">Nomor</p>
                <input type="text" name="nomor" class="form-control" value="{{ rs.nomor }}">
            </div>
            <input type="submit" value="Submit" class="btn btn-outline-info float-right mt-2">
        </form>
    </div>
</div>
{% endblock %}