medikago/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import home
from authentication.views import profile

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('auth/', include('authentication.urls'), name='authentication'),
    path('profil', profile, name="profile"),
    path('transaksi/', include('transaksi.urls'), name='transaksi'),
    path('rscabang/', include('rscabang.urls'), name='rscabang'),
    path('sesikonsultasi/', include('sesikonsultasi.urls'), name='sesikonsultasi'),
    path('poliklinik/', include('poliklinik.urls'), name='poliklinik'),
    path('resep-obat/', include('resepdanobat.urls'), name='resepdanobat')
]

poliklinik/urls.py
from django.urls import path
from . import views

app_name='poliklinik'

urlpatterns = [
    path('buat-layanan-poliklinik/', views.buat_layananPoli, name="buat_layananPoli"), #url for buat-layanan poliklinik menu
    path('daftar-layanan-poliklinik/', views.list_layananPoli, name="list_layananPoli"), #url for daftar-layanan-poliklinik menu
    path('daftar-layanan-poliklinik/update/<int:id_poli>', views.update_layananPoli, name="update_layananPoli"), #url for updating layanan poli
    path('daftar-layanan-poliklinik/delete/<int:id_poli>', views.delete_layananPoli, name="delete_layananPoli"),
    path('daftar-layanan-poliklinik/jadwal/<int:id_poli>', views.jadwal_layananPoli, name="jadwal_layananPoli"),  #url for handling button Jadwal Layanan
    path('buat-jadwal-poliklinik/', views.buat_jadwalPoli, name="buat_jadwalPoli"), #url for handling Buat Jadwal Poliklinik
    path('delete-jadwal-poliklinik/<int:id_jadwal>', views.delete_jadwalPoli, name="delete_jadwalPoli"), #url for handling Delete Jadwal Poliklinik
    path('daftar-jadwal-poliklinik/', views.daftar_jadwalPoli, name="daftar_jadwalPoli"),   #url for Daftar Jadwal Poliklinik menu
    path('daftar-jadwal-poliklinik/update/<int:id_jadwal>', views.update_jadwalPoli, name="update_jadwalPoli"),   #url for Action Update Jadwal Poliklinik
]

poliklinik/models.py
from django.db import models

# Create your models here.

poliklinik/views.py
from django.shortcuts import redirect, render
from .db import Poliklinik, JadwalPoli
from rscabang.db import RSCabang
from authentication.auth import login_required, admin_permission

'''View for Buat Layanan Poliklinik Menu'''
@login_required
@admin_permission
def buat_layananPoli(request):
    error = False
    if request.method == 'POST':
        nama = request.POST['nama']
        deskripsi = request.POST['deskripsi']
        kode_rs = request.POST['kode_rs']
        jadwal = {
            'hari' : request.POST.getlist('hari'),
            'mulai' : request.POST.getlist('jam_mulai'),
            'selesai' : request.POST.getlist('jam_selesai'),
            'kapasitas' : request.POST.getlist('kapasitas'),
            'dokter': request.POST.getlist('dokter')
        }
        try:
            Poliklinik().create_layanan_with_jadwal(nama, deskripsi, kode_rs, jadwal)
            return redirect('poliklinik:list_layananPoli')
        except:
            error = True
            pass
    list_rs = RSCabang().get_list_daftar_cabang()
    list_dokter = RSCabang().get_all_id_dokter()
    return render(request, 'buat-layananPoli.html', {'list_rs': list_rs, 'list_dokter': list_dokter, "error":error})

'''View for Daftar Layanan Poliklinik Menu'''
@login_required
def list_layananPoli(request):
    poliklinik = Poliklinik().get_all_poliklinik()
    return render(request, 'daftar-layananPoli.html', {'poliklinik': poliklinik})

'''View for Action Update Layanan Poliklinik'''
@login_required
@admin_permission
def update_layananPoli(request, id_poli):
    error= False
    detail_layanan = Poliklinik().get_detail_layanan_by_id(id_poli)[0]
    daftar_rs_cabang = RSCabang().get_all_kode_rs()
    if request.method == "POST":
        id_poliklinik = id_poli
        nama_layanan = request.POST['nama_layanan']
        deskripsi = request.POST['deskripsi']
        kode_rs = request.POST['kode_rs']
        try:
            Poliklinik().update_poliklinik(id_poliklinik,kode_rs,nama_layanan,deskripsi)
            return redirect("poliklinik:list_layananPoli")
        except:
            error = True
            pass
    return render(request, 'update-layananPoli.html', {"detail_layanan":detail_layanan, "daftar_rs_cabang":daftar_rs_cabang, "id_poli":id_poli, "error":error})

'''View for action delete Layanan Poliklinik'''
@login_required
@admin_permission
def delete_layananPoli(request, id_poli):
    if request.method == "POST":
        Poliklinik().delete(id_poli)
    return redirect('poliklinik:list_layananPoli')

'''View for Button Jadwal Layanan on Daftar Layanan Poliklinik'''
@login_required
def jadwal_layananPoli(request, id_poli):
    list_related_jadwal = JadwalPoli().get_related_jadwal(id_poli)
    return render(request, 'jadwal_layananPoli.html', {"list_related_jadwal":list_related_jadwal, "id_poli":id_poli})

'''View for Buat Jadwal Poliklinik Menu'''
@login_required
@admin_permission
def buat_jadwalPoli(request):
    daftar_hari = ["Senin", "Selasa", "Rabu", "Kamis", "Jumat", "Sabtu", "Minggu"]
    list_id_dokter = RSCabang().get_all_id_dokter()
    list_id_poliklinik = Poliklinik().get_all_id_poliklinik()
    error = False
    if request.method == "POST":
        hari = request.POST['hari']
        waktu_mulai = request.POST['waktu_mulai']
        waktu_selesai = request.POST['waktu_selesai']
        kapasitas = request.POST['kapasitas']
        id_dokter = request.POST['id_dokter']
        id_poliklinik = request.POST['id_poliklinik']
        id_jadwal = JadwalPoli().get_new_id_jadwal()
        try:
            JadwalPoli().create_new_jadwal(id_jadwal, hari, waktu_mulai, waktu_selesai, kapasitas, id_dokter, id_poliklinik)
            return redirect('poliklinik:daftar_jadwalPoli')
        except:
            error = True
            pass
    return render(request, 'buat_jadwalPoli.html', {"daftar_hari":daftar_hari, "list_id_dokter":list_id_dokter, "list_id_poliklinik":list_id_poliklinik, "error":error})

'''View for Daftar Jadwal Poliklinik Menu'''
@login_required
def daftar_jadwalPoli(request):
    list_all_jadwal = JadwalPoli().get_all_jadwal()
    return render(request, 'daftar-jadwalPoli.html', {"list_all_jadwal":list_all_jadwal})

'''View for Action Update Jadwal Poliklinik'''
@login_required
@admin_permission
def update_jadwalPoli(request, id_jadwal):
    error = False
    detail_jadwal = JadwalPoli().get_detail_jadwal_by_id(id_jadwal)[0]
    waktu_mulai_converted = detail_jadwal['waktu_mulai'].isoformat()
    waktu_selesai_converted = detail_jadwal['waktu_selesai'].isoformat()
    detail_jadwal['waktu_mulai'] = waktu_mulai_converted
    detail_jadwal['waktu_selesai'] = waktu_selesai_converted
    daftar_hari = ["Senin", "Selasa", "Rabu", "Kamis", "Jumat", "Sabtu", "Minggu"]
    list_id_dokter = RSCabang().get_all_id_dokter()
    if request.method == "POST":
        id_jadwal_poliklinik = id_jadwal
        hari = request.POST['hari']
        waktu_mulai = request.POST['waktu_mulai']
        waktu_selesai = request.POST['waktu_selesai']
        kapasitas = request.POST['kapasitas']
        id_dokter = request.POST['id_dokter']
        id_poliklinik = detail_jadwal['id_poliklinik']
        try:
            JadwalPoli().update_jadwal_poliklinik(id_jadwal_poliklinik, hari, waktu_mulai, waktu_selesai, kapasitas, id_dokter, id_poliklinik)
            return redirect("poliklinik:daftar_jadwalPoli")
        except:
            error = True
            pass
    return render(request, 'update-jadwalPoli.html', {"error":error, "detail_jadwal":detail_jadwal, "list_id_dokter":list_id_dokter, "daftar_hari":daftar_hari, "id_jadwal_poliklinik":id_jadwal})

'''View for Deleting Jadwal Poliklinik'''
@login_required
@admin_permission
def delete_jadwalPoli(request, id_jadwal):
    if request.method == "POST":
        JadwalPoli().delete_jadwal_by_id(id_jadwal)
    return redirect('poliklinik:daftar_jadwalPoli')

poliklinik/templates/buat-layananPoli.html
{% extends 'base.html' %}

{% block content %}
<div class="d-flex flex-column align-items-center mt-5">
    <h2>FORM PEMBUATAN LAYANAN POLIKLINIK</h2>
    {% if error %}
        <h3 class="text-warning">Error occured, please check your input!</h3>
    {% endif %}
    <div class=" mt-4 w-75">
        <form action="{% url 'poliklinik:buat_layananPoli' %}" class="align-items-center" method="POST">
            {% csrf_token %}
            <div class="d-flex flex-row form-group-row my-2">
                <p class="w-50">Nama Layanan</p>
                <input type="text" name="nama" class="form-control w-70" required>
            </div>
            <div class="d-flex flex-row form-group-row my-2">
                <p class="w-50">Deskripsi</p>
                <input name="deskripsi" type="text" class="form-control w-70">
            </div>
            <div class="d-flex flex-row form-group-row my-2">
                <p class="w-50">Kode RS</p>
                <select name="kode_rs" id="" class="custom-select w-70">
                    {% for rs in list_rs %}
                        <option value="{{ rs.kode_rs }}">{{ rs.kode_rs }} - {{ rs.nama }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="d-flex flex-row form-group-row my-2" >
                <p class="w-25 mr-5">Daftar Jadwal</p>
                <div class='w-55' id="jadwal">
                    <div class="d-flex flex-row form-group-row ml-5">
                        <select name="hari" id="" class="custom-select">
                            <option value="Senin" selected>Senin</option>
                            <option value="Selasa">Selasa</option>
                            <option value="Rabu">Rabu</option>
                            <option value="Kamis">Kamis</option>
                            <option value="Jumat">Jumat</option>
                            <option value="Sabtu">Sabtu</option>
                            <option value="Minggu">Minggu</option>
                        </select>
                        <span>;</span>
                        <input name="jam_mulai" value="09:00" type="time" class="form-control" placeholder="Jam mulai" required>
                        <span>-</span>
                        <input name="jam_selesai" value="12:00" type="time" class="form-control" placeholder="Jam selesai" required>
                        <span>;</span>
                        <input name="kapasitas" type="text" class="form-control" placeholder="Kapasitas" required>
                        <span>;</span>
                        <select name="dokter" id="" class="custom-select" required aria-invalid="false">
                            <option value="" selected disabled>Dokter</option>
                            {% for dokter in list_dokter %}
                                <option value="{{ dokter.id_dokter }}">{{ dokter.id_dokter }} - {{ dokter.username }}</option>
                            {% endfor %}
                        </select>
                    </div>
                </div>
                <button type="button" style="width: 80px;height: 35px;" class="btn btn-outline-warning ml-3" onclick="addJadwal()">Tambah</button>
            </div>
            <input type="submit" value="Submit" class="btn btn-outline-info float-right mt-2">
        </form>
    </div>
</div>

{% endblock %}
{% block script %}
<script>
  function addJadwal(e){
    const div = document.createElement('div');
    div.className= "d-flex flex-row form-group-row ml-5";
    div.innerHTML= `
        <select name="hari" id="" class="custom-select">
            <option value="Senin" selected>Senin</option>
            <option value="Selasa">Selasa</option>
            <option value="Rabu">Rabu</option>
            <option value="Kamis">Kamis</option>
            <option value="Jumat">Jumat</option>
            <option value="Sabtu">Sabtu</option>
            <option value="Minggu">Minggu</option>
        </select>
        <span>;</span>
        <input name="jam_mulai" value="09:00" type="time" class="form-control" placeholder="Jam mulai" required>
        <span>-</span>
        <input name="jam_selesai" value="12:00" type="time" class="form-control" placeholder="Jam selesai" required>
        <span>;</span>
        <input name="kapasitas" type="text" class="form-control" placeholder="Kapasitas" required>
        <span>;</span>
        <select name="dokter" id="" class="custom-select" required aria-invalid="false">
            <option value="" selected disabled>Dokter</option>
            {% for dokter in list_dokter %}
                <option value="{{ dokter.id_dokter }}">{{ dokter.id_dokter }} - {{ dokter.username }}</option>
            {% endfor %}
        </select>
    `;
    document.getElementById("jadwal").appendChild(div);
  }
</script>
{% endblock %}

poliklinik/templates/buat_jadwalPoli.html
{% extends 'base.html' %}

{% block content %}
<div class="d-flex flex-column align-items-center">
    <h2>FORM BUAT JADWAL LAYANAN POLIKLINIK</h2>
    {% if error %}
        <h3 class="text-warning">Error occured, please check your input!</h3>
    {% endif %}
    <div class="mt-4 w-75">
        <form action="{% url 'poliklinik:buat_jadwalPoli' %}" method="POST" class=" align-items-center">
            {% csrf_token %}
            <div class="d-flex flex-row form-group-row my-2">
                <p class="w-50">Hari</p>
                <select name="hari" id="" class="custom-select" placeholder="Pilih hari">
                    {% for nama_hari in daftar_hari %}
                        <option value="{{ nama_hari }}">{{ nama_hari }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="d-flex flex-row form-group-row my-2">
                <p class="w-50">Waktu Mulai</p>
                <input type="time" name="waktu_mulai" class="form-control" value="">
            </div>
            <div class="d-flex flex-row form-group-row my-2">
                <p class="w-50">Waktu Selesai</p>
                <input type="time" name="waktu_selesai" class="form-control" value="">
            </div>
            <div class="d-flex flex-row form-group-row my-2">
                <p class="w-50">Kapasitas</p>
                <input type="text" name="kapasitas" class="form-control" value="" placeholder="kapasitas">
            </div>
            <div class="d-flex flex-row form-group-row my-2">
                <p class="w-50">ID Dokter</p>
                <select name="id_dokter" id="" class="custom-select" placeholder="pilih id dokter">
                    {% for items in list_id_dokter %}
                        <option value="{{ items.id_dokter }}" selected>{{ items.id_dokter }} - {{ items.username }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="d-flex flex-row form-group-row my-2">
                <p class="w-50">ID Poliklinik</p>
                <select name="id_poliklinik" id="" class="custom-select" placeholder="pilih id poliklinik">
                    {% for items in list_id_poliklinik %}
                        <option value="{{ items.id_poliklinik }}">{{ items.id_poliklinik }} - {{ items.nama }}</option>
                    {% endfor %}
                </select>
            </div>
            <input type="submit" value="Submit" class="btn btn-outline-info float-right mt-2">
        </form>
    </div>
</div>
{% endblock %}

poliklinik/templates/daftar-jadwalPoli.html
{% extends 'base.html' %}

{% block content %}
<h2 class="mt-4 mb-3 ml-3">DAFTAR JADWAL LAYANAN POLIKLINIK KESELURUHAN</h1>
  <table class="table table-hover">
    <thead>
      <tr>
        <th scope="col">ID Jadwal Poliklinik</th>
        <th scope="col">Hari</th>
        <th scope="col">Waktu Mulai</th>
        <th scope="col">Waktu Selesai</th>
        <th scope="col">Kapasitas</th>
        <th scope="col">ID Dokter</th>
        <th scope="col">ID Poliklinik</th>
        {% if request.session.role == "admin" %}
          <th scope="col">Action</th>
        {% endif %}
      </tr>
    </thead>
    <tbody>
      {% for items in list_all_jadwal %}
        <tr>
          <td>{{ items.id_jadwal_poliklinik }}</td>
          <td>{{ items.hari }}</td>
          <td>{{ items.waktu_mulai }}</td>
          <td>{{ items.waktu_selesai }}</td>
          <td>{{ items.kapasitas }}</td>
          <td>{{ items.id_dokter }}</td>
          <td>{{ items.id_poliklinik }}</td>
          {% if request.session.role == "admin" %}
            <td>
              <div class="col">
                <a href="{% url 'poliklinik:update_jadwalPoli' items.id_jadwal_poliklinik %}" class="btn btn-outline-info btn-sm">Update</a>
                <form action="{% url 'poliklinik:delete_jadwalPoli' items.id_jadwal_poliklinik %}" method="POST" class="btn btn-sm">
                  {% csrf_token %}
                  <button class='btn btn-danger btn-sm' type="submit">Delete</button>
                </form>
              <div>
            </td>
          {% endif %}
        </tr>
      {% endfor %}
    </tbody>
  </table>


  {% endblock %}

poliklinik/templates/daftar-layananPoli.html
{% extends 'base.html' %}

{% block content %}
<h2 class="mt-4 mb-3 ml-3">Daftar Layanan Poliklinik</h1>
  <table class="table table-hover">
    <thead>
      <tr>
        <th scope="col">ID Layanan Poliklinik</th>
        <th scope="col">Nama</th>
        <th scope="col">Deskripsi</th>
        <th scope="col">Kode RS</th>
        <th scope="col">Jadwal</th>
        {% if request.session.role == "admin" %}
          <th scope="col">Action</th>
        {% endif %}
      </tr>
    </thead>
    <tbody>
      {% for poli in poliklinik %}
        <tr>
          <td>{{ poli.id_poliklinik }}</td>
          <td>{{ poli.nama }}</td>
          <td>{{ poli.deskripsi }}</td>
          <td>{{ poli.kode_rs_cabang }}</td>
          <td>
              <div class="col">
                  <button class='btn btn-outline-info btn-sm' onclick="window.location='jadwal/{{ poli.id_poliklinik }}'">Jadwal Layanan</button>
              <div> 
          </td>
          {% if request.session.role == "admin" %}
            <td>
              <div class="col">
              <a href="{% url 'poliklinik:update_layananPoli' poli.id_poliklinik %}" class="btn btn-outline-info btn-sm">Update</a>
              <form action="{% url 'poliklinik:delete_layananPoli' poli.id_poliklinik %}" method="POST"> 
                {% csrf_token %}
                <button class='btn btn-danger btn-sm'>Delete</button>
              </form>
              <div>
            </td>
          {% endif %}
        </tr>
      {% endfor %}
    </tbody>
  </table>


  {% endblock %}

poliklinik/templates/jadwal_layananPoli.html
{% extends 'base.html' %}

{% block content %}
<h2 class="mt-4 mb-3 ml-3">JADWAL LAYANAN POLI DENGAN ID LAYANAN POLIKLINIK {{id_poli}}</h1>
  <table class="table table-hover">
    <thead>
      <tr>
        <th scope="col">ID Jadwal Poliklinik</th>
        <th scope="col">Hari</th>
        <th scope="col">Waktu Mulai</th>
        <th scope="col">Waktu Selesai</th>
        <th scope="col">Kapasitas</th>
        <th scope="col">ID Dokter</th>
        <th scope="col">ID Poliklinik</th>
        {% if request.session.role == "admin" %}
          <th scope="col">Action</th>
        {% endif %} 
      </tr>
    </thead>
    <tbody>
      {% for items in list_related_jadwal %}
        <tr>
          <td>{{ items.id_jadwal_poliklinik }}</td>
          <td>{{ items.hari }}</td>
          <td>{{ items.waktu_mulai }}</td>
          <td>{{ items.waktu_selesai }}</td>
          <td>{{ items.kapasitas }}</td>
          <td>{{ items.id_dokter }}</td>
          <td>{{ items.id_poliklinik }}</td>
          {% if request.session.role == "admin" %}
            <td>
              <div class="col">
                <a href="{% url 'poliklinik:update_jadwalPoli' id_jadwal=items.id_jadwal_poliklinik %}" class="btn btn-outline-info btn-sm">Update</a>
                <form action="{% url 'poliklinik:delete_jadwalPoli' items.id_jadwal_poliklinik %}" method="POST" class="btn btn-sm">
                  {% csrf_token %}
                  <button class='btn btn-danger btn-sm' type="submit">Delete</button>
                </form>
              <div>
            </td>
          {% endif %}
        </tr>
      {% endfor %}
    </tbody>
  </table>


  {% endblock %}

poliklinik/templates/update-jadwalPoli.html
{% extends 'base.html' %}

{% block content %}
<div class="d-flex flex-column align-items-center">
    <h2>FORM UPDATE JADWAL LAYANAN POLIKLINIK</h2>
    {% if error %}
        <h3 class="text-warning">Error occured, please check your input!</h3>
    {% endif %}
    <div class="mt-4 w-75">
        <form action="{% url 'poliklinik:update_jadwalPoli' id_jadwal_poliklinik %}" method="POST" class=" align-items-center">
            {% csrf_token %}
            <div class="d-flex flex-row form-group-row my-2">
                <p class="w-50">ID Jadwal Layanan Poliklinik</p>
                <input type="text" name="id_jadwal_poliklinik" class="form-control"  value="{{ id_jadwal_poliklinik }}" disabled>
            </div>
            <div class="d-flex flex-row form-group-row my-2">
                <p class="w-50">Hari</p>
                <select name="hari" id="" class="custom-select">
                    <option value="{{ detail_jadwal.hari }}" selected>{{ detail_jadwal.hari }}</option>
                    {% for nama_hari in daftar_hari %}
                        {% if nama_hari != detail_jadwal.hari %}
                            <option value="{{ nama_hari }}">{{ nama_hari }}</option>
                        {% endif %}
                    {% endfor %}
                </select>
            </div>
            <div class="d-flex flex-row form-group-row my-2">
                <p class="w-50">Waktu Mulai</p>
                <input type="time" name="waktu_mulai" class="form-control" value="{{ detail_jadwal.waktu_mulai }}">
            </div>
            <div class="d-flex flex-row form-group-row my-2">
                <p class="w-50">Waktu Selesai</p>
                <input type="time" name="waktu_selesai" class="form-control" value="{{ detail_jadwal.waktu_selesai }}">
            </div>
            <div class="d-flex flex-row form-group-row my-2">
                <p class="w-50">Kapasitas</p>
                <input type="text" name="kapasitas" class="form-control" value="{{ detail_jadwal.kapasitas }}">
            </div>
            <div class="d-flex flex-row form-group-row my-2">
                <p class="w-50">ID Dokter</p>
                <select name="id_dokter" id="" class="custom-select">
                    <option value="{{ detail_jadwal.id_dokter }}" selected>{{ detail_jadwal.id_dokter }}</option>
                    {% for items in list_id_dokter %}
                        {% if items.id_dokter != detail_jadwal.id_dokter %}
                            <option value="{{ items.id_dokter }}">{{ items.id_dokter }}</option>
                        {% endif %}
                    {% endfor %}
                </select>
            </div>
            <div class="d-flex flex-row form-group-row my-2">
                <p class="w-50">ID Poliklinik</p>
                <input type="text" name="id_poli" class="form-control" value="{{ detail_jadwal.id_poliklinik }}" disabled>
            </div>
            <input type="submit" value="Update" class="btn btn-outline-info float-right mt-2">
        </form>
    </div>
</div>
{% endblock %}

poliklinik/templates/update-layananPoli.html
{% extends 'base.html' %}

{% block content %}
<div class="d-flex flex-column align-items-center">
    <h2>FORM UPDATE LAYANAN POLIKLINIK</h2>
    {% if error %}
        <h3 class="text-warning">Error occured, please check your input!</h3>
    {% endif %}
    <div class="mt-4 w-75">
        <form action="{% url 'poliklinik:update_layananPoli' id_poli %}" method="POST" class=" align-items-center">
            {% csrf_token %}
            <div class="d-flex flex-row form-group-row my-2">
                <p class="w-50">ID Poliklinik</p>
                <input type="text" class="form-control" id="disabledTextInput" value="{{ id_poli }}" disabled name="id_poliklinik">
            </div>
            <div class="d-flex flex-row form-group-row my-2">
                <p class="w-50">Nama Layanan</p>
                <input type="text" name="nama_layanan" class="form-control" value="{{ detail_layanan.nama }}">
            </div>
            <div class="d-flex flex-row form-group-row my-2">
                <p class="w-50">Deskripsi</p>
                <input type="text" name="deskripsi" class="form-control" value="{{ detail_layanan.deskripsi }}">
            </div>
            <div class="d-flex flex-row form-group-row my-2">
                <p class="w-50">Kode RS Cabang Penyedia Layanan</p>
                <select name="kode_rs" id="" class="custom-select">
                    <option value="{{ detail_layanan.kode_rs_cabang }}" selected>{{ detail_layanan.kode_rs_cabang }}</option>
                    {% for items in daftar_rs_cabang %}
                        {% if items.kode_rs != detail_layanan.kode_rs_cabang %}
                            <option value="{{ items.kode_rs }}">{{ items.kode_rs }}</option>
                        {% endif %}
                    {% endfor %}
                </select>
            </div>
            <input type="submit" value="Submit" class="btn btn-outline-info float-right mt-2">
        </form>
    </div>
</div>
{% endblock %}