medikago/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import home
from authentication.views import profile

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('auth/', include('authentication.urls'), name='authentication'),
    path('profil', profile, name="profile"),
    path('transaksi/', include('transaksi.urls'), name='transaksi'),
    path('rscabang/', include('rscabang.urls'), name='rscabang'),
    path('sesikonsultasi/', include('sesikonsultasi.urls'), name='sesikonsultasi'),
    path('poliklinik/', include('poliklinik.urls'), name='poliklinik'),
    path('resep-obat/', include('resepdanobat.urls'), name='resepdanobat')
]

sesikonsultasi/urls.py
from django.urls import path
from . import views

app_name='sesikonsultasi'
urlpatterns = [
    path('add_sesi/', views.add_sesi, name='add_sesi'),
    path('daftar_sesi/', views.daftar_sesi, name='daftar_sesi'),
    path('daftar_sesi/<int:idkonsultasi>/', views.update_sesi, name='update_sesi'),
    path('daftar_sesi/delete_sesi/<int:idkonsultasi>/', views.delete_sesi, name='delete_sesi'),
]

sesikonsultasi/models.py
from django.db import models

# Create your models here.

sesikonsultasi/views.py
from django.shortcuts import render, redirect
from .db import SesiKonsultasi
from authentication.auth import login_required, admin_permission

@login_required
@admin_permission
def add_sesi(request):
    if request.method == 'POST':
        no_rekam_medis = request.POST['no_rekam_medis']
        id_transaksi = request.POST['id_transaksi']
        tanggal = request.POST['tanggal']
        SesiKonsultasi().create_sesi_konsultasi(no_rekam_medis, id_transaksi, tanggal)
        return redirect("sesikonsultasi:daftar_sesi")
    else:
        list_transaksi = SesiKonsultasi().get_transaksi()
        list_no_rekam_medis = SesiKonsultasi().get_no_rekam_medis()
        return render(request, 'add_sesi.html', {'list_transaksi':list_transaksi, 'list_no_rekam_medis':list_no_rekam_medis})
        
@login_required
def daftar_sesi(request):
    if request.session['role'] == 'admin' :
        list_sesi_konsultasi = SesiKonsultasi().get_sesi_konsultasi_from_admin()
    elif request.session['role'] == 'pasien':
        list_sesi_konsultasi = SesiKonsultasi().get_sesi_konsultasi_from_pengguna(request.session['username'])
    else :
        list_sesi_konsultasi = SesiKonsultasi().get_sesi_konsultasi_from_dokter(request.session['username'])
    return render(request, 'list_sesi_konsultasi.html', {"list_sesi_konsultasi":list_sesi_konsultasi})

@login_required
@admin_permission
def update_sesi(request, idkonsultasi):
    if request.method == 'POST':
        tanggal = request.POST['tanggal']
        status = request.POST['status']
        SesiKonsultasi().update_detailed_sesi_konsultasi(idkonsultasi, tanggal, status)
        return redirect("sesikonsultasi:daftar_sesi")
    else :
        detail_sesi_konsultasi = SesiKonsultasi().get_detailed_sesi_konsultasi(idkonsultasi)
        detail = detail_sesi_konsultasi[0]
        tanggal = str(detail['tanggal'])
        return render(request, 'update_sesi_konsultasi.html', {'detail':detail, 'tanggal':tanggal})

@login_required
@admin_permission
def delete_sesi(request, idkonsultasi):
    if request.method == 'POST':
        SesiKonsultasi().delete(idkonsultasi)
    return redirect("sesikonsultasi:daftar_sesi")

sesikonsultasi/templates/add_sesi.html
{% extends 'base.html' %}

{% block content %}
<div class="d-flex flex-column align-items-center">
    <h2>FORM RESERVASI SESI KONSULTASI</h2>
    <div class=" mt-4 w-50">
        <form action="{% url 'sesikonsultasi:add_sesi' %}" method="POST" class="align-items-center">
            {% csrf_token %}
            <div class="d-flex flex-row form-group-row my-2">
                <p class="w-25">No Rekam Medis</p>
                <select name="no_rekam_medis" id="" class="custom-select w-75">
                    {% for no in list_no_rekam_medis %}
                    <option value="{{ no.no_rekam_medis }}">{{ no.no_rekam_medis }} - {{ no.username }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="d-flex flex-row form-group-row my-2">
                <p class="w-25">Tanggal</p>
                <input type="date" class="form-control w-75" name="tanggal">
            </div>
            <div class="d-flex flex-row form-group-row my-2">
                <p class="w-25">ID Transaksi</p>
                <select name="id_transaksi" id="" class="custom-select w-75">
                    {% for transaksi in list_transaksi %}
                    <option value="{{ transaksi.id_transaksi }}">{{ transaksi.id_transaksi }}</option>
                    {% endfor %}
                </select>
            </div>
            <input type="submit" value="Submit" class="btn btn-outline-info float-right mt-2">
        </form>
    </div>
</div>






{% endblock %}

sesikonsultasi/templates/list_sesi_konsultasi.html
{% extends 'base.html' %}

{% block content %}
<h2 class="mt-4 mb-3 ml-3">Daftar Sesi Konsultasi</h1>
  <p class="mt-4 mb-3 ml-3">{{ request.session.username }} - {{ request.session.role }}</p>
  <table class="table table-hover">
    <thead>
      <tr>
        <th scope="col-1">ID Konsultasi</th>
        <th scope="col-2">No. Pasien</th>
        <th scope="col-2">Tanggal</th>
        <th scope="col-2">Biaya</th>
        <th scope="col-2">Status</th>
        <th scope="col-1">ID Transaksi</th>
        {% if request.session.role == "admin" %}
        <th scope="col-2">Action</th>
        {% endif %}
      </tr>
    </thead>
    <tbody>
      {% for sesi in list_sesi_konsultasi %}
      <tr>
        <td>{{ sesi.id_konsultasi }}</td>
        <td>{{ sesi.no_rekam_medis_pasien }}</td>
        <td>{{ sesi.tanggal }}</td>
        <td>Rp {{ sesi.biaya }}</td>
        <td>{{ sesi.status }}</td>
        <td>{{ sesi.id_transaksi }}</td>
        {% if request.session.role == "admin" %}
        <td>
          <div class="col">
            <button class='btn btn-outline-info btn-sm' onclick="window.location={{ sesi.id_konsultasi }}">Update</button>
            <form method="POST" action="{% url 'sesikonsultasi:delete_sesi' sesi.id_konsultasi %}">
              {% csrf_token %}
              <button class='btn btn-danger' type="submit">Delete</button>
            </form>
          <div>
        </td>
        {% endif %}
      </tr>
      {% endfor %}
    </tbody>
  </table>


  {% endblock %}

sesikonsultasi/templates/update_sesi_konsultasi.html
{% extends 'base.html' %}

{% block content %}
<div class="d-flex flex-column align-items-center">
    <h2>FORM UPDATE SESI KONSULTASI</h2>
    <div class=" mt-4 w-75">
        <form action="{% url 'sesikonsultasi:update_sesi' detail.id_konsultasi %}" class=" align-items-center" method="POST">
            {% csrf_token %}
            <div class="d-flex flex-row form-group-row my-2">
                <p class="w-50">ID Konsultasi</p>
                <input type="text" class="form-control" id="disabledTextInput" placeholder="{{ detail.id_konsultasi }}" disabled>
            </div>
            <div class="d-flex flex-row form-group-row my-2">
                <p class="w-50">No Rekam Medis Pasien</p>
                <input type="text" class="form-control" id="disabledTextInput" placeholder="{{ detail.no_rekam_medis_pasien }}" disabled>
            </div>
            <div class="d-flex flex-row form-group-row my-2">
                <p class="w-50">Tanggal</p>
                <input type="date" name="tanggal" class="form-control" value="{{ tanggal }}">
            </div>
            <div class="d-flex flex-row form-group-row my-2">
                <p class="w-50">Biaya</p>
                <input type="text" class="form-control" id="disabledTextInput" placeholder="Rp {{ detail.biaya }}" disabled>
            </div>
            <div class="d-flex flex-row form-group-row my-2">
                <p class="w-50">Status</p>
                <select name="status"  class="custom-select">
                    <option value="BOOKED">Booked</option>
                    <option value="DONE">Done</option>
                    <option value="CANCELED">Canceled</option>
                </select>
            </div>
            <input type="submit" value="Submit" class="btn btn-outline-info float-right mt-2">
        </form>
    </div>
</div>






{% endblock %}