medikago/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import home
from authentication.views import profile

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('auth/', include('authentication.urls'), name='authentication'),
    path('profil', profile, name="profile"),
    path('transaksi/', include('transaksi.urls'), name='transaksi'),
    path('rscabang/', include('rscabang.urls'), name='rscabang'),
    path('sesikonsultasi/', include('sesikonsultasi.urls'), name='sesikonsultasi'),
    path('poliklinik/', include('poliklinik.urls'), name='poliklinik'),
    path('resep-obat/', include('resepdanobat.urls'), name='resepdanobat')
]

resepdanobat/urls.py
from django.urls import path
from . import views

app_name='resepdanobat'

urlpatterns = [
    path('buat-resep/', views.buat_resep, name="buat_resep"),
    path('daftar-resep/', views.daftar_resep, name="daftar_resep"),
    path('daftar-resep/delete-resep/<int:no_resep>/', views.delete_resep, name="delete_resep"),
    path('buat-obat/', views.buat_obat, name="buat_obat"),
    path('daftar-obat/', views.daftar_obat, name="daftar_obat"),
    path('daftar-obat/<str:kode>/', views.update_obat, name="update_obat"),
    path('daftar-obat/delete-obat/<int:kode>/', views.delete_obat, name="delete_obat"),
]

resepdanobat/models.py
from django.db import models

# Create your models here.

resepdanobat/views.py
from django.shortcuts import render, redirect
from django.db import IntegrityError
from .db import ResepdanObat
from authentication.auth import login_required, admin_permission


'''View for Buat Resep'''
@login_required
@admin_permission
def buat_resep(request):
    if request.method == 'POST':
        id_konsultasi = request.POST['id_konsultasi']
        id_transaksi = request.POST['id_transaksi']
        daftar_kode_obat = request.POST.getlist('daftar_kode_obat')
        ResepdanObat().buat_resep(id_konsultasi, id_transaksi, daftar_kode_obat)
        return redirect("resepdanobat:daftar_resep")
    else:
        list_id_konsultasi = ResepdanObat().get_id_konsultasi()
        list_id_transaksi = ResepdanObat().get_id_transaksi()
        list_kode_obat = ResepdanObat().get_kode_obat()
        return render(request, 'buat-resep.html', {'list_id_konsultasi':list_id_konsultasi, 'list_id_transaksi':list_id_transaksi, 'list_kode_obat':list_kode_obat})

'''View for Daftar Resep'''
@login_required
def daftar_resep(request):
    daftar_resep_dan_obat = ResepdanObat().get_daftar_resep()
    return render(request, 'daftar-resep.html', {'daftar_resep_dan_obat':daftar_resep_dan_obat})

'''View for Delete Resep'''
@login_required
@admin_permission
def delete_resep(request, no_resep):
    if request.method == 'POST':
        ResepdanObat().delete_resep(no_resep)
    return redirect("resepdanobat:daftar_resep")

'''View for Buat Obat'''
@login_required
@admin_permission
def buat_obat(request):
    if request.method == 'POST':
        try:
            kode = request.POST['kode']
            stock = request.POST['stock']
            harga = request.POST['harga']
            komposisi = request.POST['komposisi']
            bentuk = request.POST['bentuk']
            merek = request.POST['merek']
            ResepdanObat().buat_obat(kode, stock, harga, komposisi, bentuk, merek)
            return redirect("resepdanobat:daftar_obat")
        except IntegrityError as e:
            return render(request, 'buat-obat.html', {'error':True})
    else:
        return render(request, 'buat-obat.html')

'''Views for Daftar Obat'''
@login_required
def daftar_obat(request):
    daftar_obat = ResepdanObat().get_daftar_obat()
    return render(request, 'daftar-obat.html', {'daftar_obat':daftar_obat})

'''Views to Update Obat'''
@login_required
@admin_permission
def update_obat(request, kode):
    if request.method == 'POST':
        stok = request.POST['stok']
        harga = request.POST['harga']
        komposisi = request.POST['komposisi']
        bentuk_sediaan = request.POST['bentuk_sediaan']
        merk_dagang = request.POST['merk_dagang']
        ResepdanObat().update_obat(kode, stok, harga, komposisi, bentuk_sediaan, merk_dagang)
        return redirect("resepdanobat:daftar_obat")
    else:
        info_obat = ResepdanObat().get_info_obat(kode)
        return render(request, 'update-obat.html', {'info_obat':info_obat})

'''Views to Delete Obat'''
@login_required
@admin_permission
def delete_obat(request, kode):
    if request.method == 'POST':
        kode = int(kode)
        ResepdanObat().delete_obat(kode)
    return redirect("resepdanobat:daftar_obat")

resepdanobat/templates/buat-obat.html
{% extends 'base.html' %}

{% block content %}
<div class="d-flex flex-column align-items-center mt-5">
    <h2>FORM PEMBUATAN OBAT</h2>
    <div class=" mt-4 w-50">
        <form method="POST" action="{% url 'resepdanobat:buat_obat' %}" class="align-items-center">
            {% csrf_token %}
            <div class="d-flex flex-row form-group-row my-2">
                <p class="w-25">Kode</p>
                <input type="number" class="form-control w-75" name="kode" required>
            </div>
            <div class="d-flex flex-row form-group-row my-2">
                <p class="w-25">Stok</p>
                <input type="number" class="form-control w-75" name="stock" required>
            </div>
            <div class="d-flex flex-row form-group-row my-2">
                <p class="w-25">Harga</p>
                <input type="number" class="form-control w-75" name="harga" required>
            </div>
            <div class="d-flex flex-row form-group-row my-2">
                <p class="w-25">Komposisi</p>
                <input type="text" class="form-control w-75" name="komposisi">
            </div>
            <div class="d-flex flex-row form-group-row my-2">
                <p class="w-25">Bentuk Sediaan</p>
                <input type="text" class="form-control w-75" name="bentuk" required>
            </div>
            <div class="d-flex flex-row form-group-row my-2">
                <p class="w-25">Merek Dagang</p>
                <input type="text" class="form-control w-75" name="merek" required>
            </div>
            <input type="submit" value="Submit" class="btn btn-outline-info float-right mt-2">
        </form>
    </div>
    {% if error %}
    <div class="alert alert-danger" role="alert">Kode sudah diambil, ganti kode anda</div>
    {% endif %}
</div>

{% endblock %}

resepdanobat/templates/buat-resep.html
{% extends 'base.html' %}

{% block content %}
<div class="d-flex flex-column align-items-center mt-5">
    <h2>FORM PEMBUATAN RESEP</h2>
    <div class="mt-4 w-25">
        <form action="{% url 'resepdanobat:buat_resep' %}" method="POST" class="align-items-center">
            {% csrf_token %}
            <div class="d-flex flex-row form-group-row my-2">
                <p class="w-50">ID Konsultasi</p>
                <select name="id_konsultasi" id="" class="custom-select w-75">
                    {% for id in list_id_konsultasi %}
                    <option value="{{ id.id_konsultasi }}">{{ id.id_konsultasi }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="d-flex flex-row form-group-row my-2">
                <p class="w-50">ID Transaksi</p>
                <select name="id_transaksi" id="" class="custom-select w-75">
                    {% for id in list_id_transaksi %}
                    <option value="{{ id.id_transaksi }}">{{ id.id_transaksi }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="form-group my-2" id="daftar_kode_obat">
                <p class="w-50">Daftar Kode Obat</p>
                <button type="button" class="btn btn-outline-warning mr-2 float-left" onclick="daftarkodeobat(); this.disabled=true"><b>+</b></button>
                <select name="daftar_kode_obat" id="" class="custom-select w-75">
                    {% for kode in list_kode_obat %}
                    <option value="{{ kode.kode }}">{{ kode.kode }} - {{ kode.merk_dagang }}</option>
                    {% endfor %}
                </select>
            </div>
            <input type="submit" value="Submit" class="btn btn-outline-info float-right mt-3 mb-3 w-25">
        </form>
    </div>
</div>

{% endblock %}

{% block script %}
<script>
  function daftarkodeobat(e){
    const div = document.createElement('div');
    div.className= "d-flex flex-row form-group-row my-2";
    div.innerHTML= `
                <button type="button" class="btn btn-outline-warning mr-2 float-left" onclick="daftarkodeobat(); this.disabled=true">+</button>
                <select name="daftar_kode_obat" id="" class="custom-select w-75">
                    {% for kode in list_kode_obat %}
                    <option value="{{ kode.kode }}">{{ kode.kode }} - {{ kode.merk_dagang }}</option>
                    {% endfor %}
                </select>
    `;
    document.getElementById("daftar_kode_obat").appendChild(div);
  }
</script>
{% endblock %}

resepdanobat/templates/daftar-obat.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<h1 class="d-flex justify-content-center mt-4 mb-3">Daftar Obat</h1>
<button class='btn btn-success mb-3 float-right mr-5' onclick="window.location='/resep-obat/buat-obat'"><span class="bold"></span>Buat Obat</button>
<table class="table table-hover mx-5" style="width: 95%; text-align: center;">
    <thead>
    <tr>
      <th scope="col">Kode</th>
      <th scope="col">Stok</th>
      <th scope="col">Harga</th>
      <th scope="col">Komposisi</th>
      <th scope="col">Bentuk Sediaan</th>
      <th scope="col">Merk Dagang</th>
      {% if request.session.role == "admin" %}
      <th scope="col">Action</th>
      {% endif %}
    </tr>
  </thead>
  <tbody>
    {% for obat in daftar_obat %}
    <tr>
      <th scope="row">{{ obat.kode }}</th>
      <td>{{ obat.stok}}</td>
      <td style="text-align: center;">Rp {{ obat.harga }}</td>
      <td>{{ obat.komposisi }}</td>
      <td>{{ obat.bentuk_sediaan }}</td>
      <td>{{ obat.merk_dagang}}</td>
      {% if request.session.role == "admin" %}
      <td>
        <button class='btn btn-outline-info' onclick="window.location={{ obat.kode }}">Update</button>
        <form method="POST" action="{% url 'resepdanobat:delete_obat' obat.kode %}">
          {% csrf_token %}
          <button class='btn btn-danger mt-1'>Delete</button>
        </form>
      </td>
      {% endif %}
    </tr>
    {% endfor %}
</tbody>
</table>
{% endblock %}

resepdanobat/templates/daftar-resep.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<link rel="stylesheet" type="text/css" href="{% static "css/style-sam.css" %}"/>
<h1 class="d-flex justify-content-center mt-4 mb-3">Daftar Resep</h1>
<p class="d-flex justify-content-center mt-4 mb-3">{{ request.session.username }} - {{ request.session.role }}</p>
<button class='btn btn-success mb-3 float-right mr-5' onclick="window.location='/resep-obat/buat-resep'"><span class="bold"></span>Buat Resep</button>
<table class="table table-hover mx-5" style="width: 95%; text-align: center;">
    <thead>
    <tr>
      <th scope="col">No. Resep</th>
      <th scope="col">Total Harga</th>
      <th scope="col">ID Konsultasi</th>
      <th scope="col">ID Transaksi</th>
      <th scope="col">Daftar Obat</th>
      {% if request.session.role == "admin" %}
      <th scope="col">Action</th>
      {% endif %}
    </tr>
  </thead>
  <tbody>
    {% for rw in daftar_resep_dan_obat %}
      <tr>
      <th scope="row">{{ rw.no_resep }}</th>
      <td style="text-align: center;">Rp {{ rw.total_harga }}</td>
      <td>{{ rw.id_konsultasi }}</td>
      <td>{{ rw.id_transaksi }}</td>
      <td>{{ rw.kodeobat }}</td>
    {% if request.session.role == "admin" %}
      <td>
        <button class='btn btn-outline-info'>Update</button>
        <form method="POST" action="{% url 'resepdanobat:delete_resep' rw.no_resep %}">
          {% csrf_token %}
          <button class='btn btn-danger mt-1'>Delete</button>
        </form>
      </td>
    {% endif %}
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock %}

resepdanobat/templates/update-obat.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="d-flex flex-column align-items-center mt-5">
    <h2>FORM UPDATE OBAT</h2>
    <div class="mt-4 w-50">
        <form method="POST" action="{% url 'resepdanobat:update_obat' info_obat.kode %}" class="align-items-center">
            {% csrf_token %}
            <div class="d-flex flex-row form-group-row my-2">
                <p class="w-25">Kode Obat</p>
                <input type="text" class="form-control w-75" value="{{ info_obat.kode }}" disabled>
            </div>
            <div class="d-flex flex-row form-group-row my-2">
                <p class="w-25">Stok</p>
                <input type="number" class="form-control w-75" name="stok" placeholder="{{ info_obat.stok }}" required>
            </div>
            <div class="d-flex flex-row form-group-row my-2">
                <p class="w-25">Harga</p>
                <input type="number" class="form-control w-75" name="harga" placeholder="{{ info_obat.harga }}" required>
            </div>
            <div class="d-flex flex-row form-group-row my-2">
                <p class="w-25">Komposisi</p>
                <input type="text" class="form-control w-75" name="komposisi"  placeholder="{{ info_obat.komposisi }}">
            </div>
            <div class="d-flex flex-row form-group-row my-2">
                <p class="w-25">Bentuk Sediaan</p>
                <input type="text" class="form-control w-75" name="bentuk_sediaan" placeholder="{{ info_obat.bentuk_sediaan }}" required>
            </div>
            <div class="d-flex flex-row form-group-row my-2">
                <p class="w-25">Merek Dagang</p>
                <input type="text" class="form-control w-75" name="merk_dagang" placeholder="{{ info_obat.merk_dagang }}" required>
            </div>
            <input type="submit" value="Submit" class="btn btn-outline-info float-right mt-2">
        </form>
    </div>
</div>
{% endblock %}